# Generated by Django 3.2.7 on 2022-09-07 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotelapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='code',
            table='list_code',
        ),
    ]
