# Generated by Django 3.2.7 on 2022-10-03 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotelapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'db_table': 'type_books',
            },
        ),
        migrations.RenameField(
            model_name='bookroom',
            old_name='code_pay',
            new_name='code',
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='discount',
            name='percent',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='TimeHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
                ('is_hours', models.CharField(blank=True, max_length=20, null=True)),
                ('is_date', models.CharField(blank=True, max_length=20, null=True)),
                ('type_book', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hotelapp.typebook')),
            ],
            options={
                'db_table': 'time_hours',
            },
        ),
    ]
