# Generated by Django 3.2.7 on 2022-09-07 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotelapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookroom',
            old_name='code',
            new_name='code_pay',
        ),
    ]
