# Generated by Django 3.2.7 on 2022-10-03 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotelapp', '0005_auto_20221003_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookroom',
            name='code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hotelapp.listcode'),
        ),
        migrations.AlterField(
            model_name='bookroom',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hotelapp.customer'),
        ),
    ]
